/**
 * User: pisti
 * Date: 2013.11.08.
 * Time: 15:32
 * To change this template use File | Settings | File Templates.
 */
/**
 classlist
 */
/*! @source http://purl.eligrey.com/github/classList.js/blob/master/classList.js*/
if("document" in self&&!("classList" in document.createElement("_")&&"classList" in document.createElementNS("http://www.w3.org/2000/svg","svg"))){(function(j){"use strict";if(!("Element" in j)){return}var a="classList",f="prototype",m=j.Element[f],b=Object,k=String[f].trim||function(){return this.replace(/^\s+|\s+$/g,"")},c=Array[f].indexOf||function(q){var p=0,o=this.length;for(;p<o;p++){if(p in this&&this[p]===q){return p}}return -1},n=function(o,p){this.name=o;this.code=DOMException[o];this.message=p},g=function(p,o){if(o===""){throw new n("SYNTAX_ERR","An invalid or illegal string was specified")}if(/\s/.test(o)){throw new n("INVALID_CHARACTER_ERR","String contains an invalid character")}return c.call(p,o)},d=function(s){var r=k.call(s.getAttribute("class")),q=r?r.split(/\s+/):[],p=0,o=q.length;for(;p<o;p++){this.push(q[p])}this._updateClassName=function(){s.setAttribute("class",this.toString())}},e=d[f]=[],i=function(){return new d(this)};n[f]=Error[f];e.item=function(o){return this[o]||null};e.contains=function(o){o+="";return g(this,o)!==-1};e.add=function(){var s=arguments,r=0,p=s.length,q,o=false;do{q=s[r]+"";if(g(this,q)===-1){this.push(q);o=true}}while(++r<p);if(o){this._updateClassName()}};e.remove=function(){var t=arguments,s=0,p=t.length,r,o=false;do{r=t[s]+"";var q=g(this,r);if(q!==-1){this.splice(q,1);o=true}}while(++s<p);if(o){this._updateClassName()}};e.toggle=function(p,q){p+="";var o=this.contains(p),r=o?q!==true&&"remove":q!==false&&"add";if(r){this[r](p)}return !o};e.toString=function(){return this.join(" ")};if(b.defineProperty){var l={get:i,enumerable:true,configurable:true};try{b.defineProperty(m,a,l)}catch(h){if(h.number===-2146823252){l.enumerable=false;b.defineProperty(m,a,l)}}}else{if(b[f].__defineGetter__){m.__defineGetter__(a,i)}}}(self))};

/**
 dataset
 */
if(!Function.prototype.bind){Function.prototype.bind=function(e){"use strict";if(typeof this!=="function"){throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable")}var t=Array.prototype.slice.call(arguments,1),n=this,r=function(){},i=function(){return n.apply(this instanceof r&&e?this:e,t.concat(Array.prototype.slice.call(arguments)))};r.prototype=this.prototype;i.prototype=new r;return i}}(function(){"use strict";var e=Object.prototype,t=e.__defineGetter__,n=e.__defineSetter__,r=e.__lookupGetter__,i=e.__lookupSetter__,s=e.hasOwnProperty;if(t&&n&&r&&i){if(!Object.defineProperty){Object.defineProperty=function(e,o,u){if(arguments.length<3){throw new TypeError("Arguments not optional")}o+="";if(s.call(u,"value")){if(!r.call(e,o)&&!i.call(e,o)){e[o]=u.value}if(s.call(u,"get")||s.call(u,"set")){throw new TypeError("Cannot specify an accessor and a value")}}if(!(u.writable&&u.enumerable&&u.configurable)){throw new TypeError("This implementation of Object.defineProperty does not support"+" false for configurable, enumerable, or writable.")}if(u.get){t.call(e,o,u.get)}if(u.set){n.call(e,o,u.set)}return e}}if(!Object.getOwnPropertyDescriptor){Object.getOwnPropertyDescriptor=function(e,t){if(arguments.length<2){throw new TypeError("Arguments not optional.")}t+="";var n={configurable:true,enumerable:true,writable:true},o=r.call(e,t),u=i.call(e,t);if(!s.call(e,t)){return n}if(!o&&!u){n.value=e[t];return n}delete n.writable;n.get=n.set=undefined;if(o){n.get=o}if(u){n.set=u}return n}}if(!Object.defineProperties){Object.defineProperties=function(e,t){var n;for(n in t){if(s.call(t,n)){Object.defineProperty(e,n,t[n])}}}}}})();if(!document.documentElement.dataset&&(!Object.getOwnPropertyDescriptor(Element.prototype,"dataset")||!Object.getOwnPropertyDescriptor(Element.prototype,"dataset").get)){var propDescriptor={enumerable:true,get:function(){"use strict";var e,t=this,n,r,i,s,o,u=this.attributes,a=u.length,f=function(e){return e.charAt(1).toUpperCase()},l=function(){return this},c=function(e,t){return typeof t!=="undefined"?this.setAttribute(e,t):this.removeAttribute(e)};try{(({})).__defineGetter__("test",function(){});n={}}catch(h){n=document.createElement("div")}for(e=0;e<a;e++){o=u[e];if(o&&o.name&&/^data-\w[\w\-]*$/.test(o.name)){r=o.value;i=o.name;s=i.substr(5).replace(/-./g,f);try{Object.defineProperty(n,s,{enumerable:this.enumerable,get:l.bind(r||""),set:c.bind(t,i)})}catch(p){n[s]=r}}}return n}};try{Object.defineProperty(Element.prototype,"dataset",propDescriptor)}catch(e){propDescriptor.enumerable=false;Object.defineProperty(Element.prototype,"dataset",propDescriptor)}}
